### ISSUE TITLE
Support vento templating within content files (html or markdown files)

### ISSUE THREAD

**Issue by Brixy** [oscarotero/vento#10]
Thank you very much for vento! It is so ‘simple’, sane and modern compared to other template languages. I am converting almost a dozen web projects to vento (from Nunjucks or Liquid).

---

I would like to use vento in content files, i.e. `.md` and `.html` files.

A simple use case would be an iterator in a `blog.html` file:

```
{{ for item of pages }}
…
{{ /for }}
```

Basically it works as expected. Yet vento throws an error if a content file contains

- a curly brace or (e.g. if a file contains JS)
- a backtick (e.g. if a file contains a markdown code block).

Would it be possible to only call vento within `{{}}`? (Nunjucks does not break for the same use case.)

Thank you very much.

**Comment by oscarotero** [comment]
Vento should be called only within `{{` and `}}` tags. Can I see a example of a breaking code?

**Comment by Brixy** [comment]
Thanks for your reply!

This works (as a excerpt from an HTML or markdown file):

```
const result = await env.runString("<h1>Test</h1><script>let name = 'Gandalf'; console.log('Hi', name, '.');</script>");
```

But this fails:

```
const result = await env.runString("<h1>Test</h1><script>let name = 'Gandalf'; console.log(`Hi ${name}.`);</script>");
```

**Comment by oscarotero** [comment]
Ok, I'll take a look.
Thanks!

**Comment by oscarotero** [comment]
v0.7.2 was released, including a fix for this issue.

**Comment by Brixy** [comment]
> v0.7.2 was released, including a fix for this issue.

Wow, thank you very much. Everything is working as expected.
