### ISSUE TITLE
groupBy filter

### ISSUE THREAD

**Issue by Brixy** [oscarotero/vento#11]
This is a second post today ;-)  and probably not a vento issue but a question.

Nunjucks has a `groupby` filter:

```
{% for year, pages in pages | groupby("year") %}
…
{% endfor %}
```

How is it possible to do something comparable in vento using a filter script? 

Thanks a lot!

P.S.: Please just close this issue if this is just a JS but not a vento related question.

**Comment by oscarotero** [comment]
Many Nunjucks filters can be replaced by simple javascript functions.
In your example, you can use the [Array.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) function:

```
{{ for year, pages of pages.sort((a, b) => a.year - b.year) }}
...
{{ /for }}
```

Or use a pipe if you prefer:

```
{{ for year, pages of pages |> sort((a, b) => a.year - b.year) }}
...
{{ /for }}
```

It's also possible to register filters in vento, so you could do something like this:

```js
env.filters.groupby = function (arr, key) {
  return arr.sort((a, b) => a[key] - b[key]);
}
```

An now you can use it:

```
{{ for year, pages of pages |> groupby("year") }}
...
{{ /for }}
```

**Comment by Brixy** [comment]
Excellent! Thanks a lot.

I forgot how JS-ish vento is.

**Comment by dogfuntom** [comment]
A sample for [Lume](https://github.com/lumeland):

```typescript
import { intersect } from '@std/collections'
import { Environment } from 'lume/deps/vento.ts'
site.hooks.vento((vento: Environment) => {
  Object.assign(vento.filters, { intersect })
})
``` 

Warning: I stumbled on it by tinkering and thus not sure how idiomatic is it.
