### ISSUE TITLE
Backticks in content

### ISSUE THREAD

**Issue by dz4k** [oscarotero/vento#12]
Using backticks in the page content causes syntax errors:

```
missing.css is the CSS library we wished already existed.
Add it to your website: `<link rel="stylesheet" href="https://unpkg.com/missing.css@{{version}}/dist/missing.min.css">`{.lang-html}
```

```
SyntaxError: Unexpected token '{'
```

**Comment by oscarotero** [comment]
@dz4k Yes, It was fixed in v0.7.2.

The last version of Lume uses v0.7.1 so quick workaround is to configure the import map to replace it with the last version.

**Comment by dz4k** [comment]
In 0.7.2, there is a slightly different bug where including the string `` \` `` causes the same issue.

**Comment by oscarotero** [comment]
Mmm, I just added [this test](https://github.com/oscarotero/vento/commit/717edaa86aeaf822304f16c38c1f22d651f83fe8) and it works fine.
Can I have an example of content causing the same issue?

**Comment by dz4k** [comment]
```
{{ set version = '1.0.13' }}

missing.css is the CSS library we wished already existed.
Add it to your website: \`<link rel="stylesheet" href="https://unpkg.com/missing.css@{{version}}/dist/missing.min.css">\`{.lang-html}
```

In the test case, the backslash gets eaten by JavaScript and the test is the same as the one above:

```
"\`" === "`"
true 
```

**Comment by oscarotero** [comment]
Okay, I think it's fixed now.
Can you check it before releasing a new version?

**Comment by dz4k** [comment]
Works on my end.

(p.s. I think this can be made simpler using JSON.stringify -- lmk if you want a PR).

**Comment by oscarotero** [comment]
@dz4k Oh, I had not thought of it. Please, feel free to do a PR.

**Comment by oscarotero** [comment]
v0.7.3 released. Thanks for your help!

**Comment by Brixy** [comment]
Before this merge there were some issues with KaTeX and MathJax. Now everything is working. Thanks, guys.
