### ISSUE TITLE
Can't get it functioning on Node

### ISSUE THREAD

**Issue by uncenter** [oscarotero/vento#16]
**./index.js**
```js
import vento from "ventojs";

const vto = vento();
const template = vto.load("my-template.vto");

const result = template({ title: "Hello world" });
console.log(result.content);
```

**./my-template.vto**
```njk
{{ title }}
```

**Output:**
```
file:///.../index.js:6
const result = template({ title: "Hello world" });
               ^

TypeError: template is not a function
    at file:///.../index.js:6:16
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async loadESM (node:internal/process/esm_loader:40:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.5.1
```

Using the example right from the README... what am I doing wrong?
I also noticed there aren't any types? And are there plans for a CJS version?

**Comment by oscarotero** [comment]
Sorry, the examples in the README are wrong: Vento is async so you need the `await` keyword. This must work:

```js
import vento from "ventojs";

const vto = vento();
const template = await vto.load("my-template.vto");

const result = await template({ title: "Hello world" });
console.log(result.content);
```

> I also noticed there aren't any types? 
Types are in `mod.d.ts`.

> And are there plans for a CJS version?
I'm using [dnt](https://github.com/denoland/dnt) to generate the NPM package, I have to investigate if it's possible to define two targets.

**Comment by uncenter** [comment]
Closed by 0682490af773ff11cb7823ae30d374a07236d2da and fa5c5a2bd2b65a6ace18c44ce3d79acd8ac5565a.

**Comment by uncenter** [comment]
Can you publish the CJS version to NPM?

**Comment by oscarotero** [comment]
Done!

**Comment by uncenter** [comment]
@oscarotero I'm not going to reopen this again but is there any way to have a proper default export for the CJS version? Looks like there is an issue on the `dnt` repo about this: https://github.com/denoland/dnt/issues/239

```js
const vento = require("ventojs").default;
```
