### ISSUE TITLE
Disabling `useWith` does not work

### ISSUE THREAD

**Issue by Mabi19** [oscarotero/vento#25]
This line
https://github.com/oscarotero/vento/blob/750f41d42b3f73e91dd8a19dbe4be6ed7734ee28/mod.ts#L32 always sets it to `true` (`anything || true` is `true` by definition) - this should probably be nullish coalescing: `anything ?? true`

**Comment by oscarotero** [comment]
Good catch, thank you!
I just released a new patch to fix this.
