### ISSUE TITLE
Keep `std` in sync with `lumeland/lume`

### ISSUE THREAD

**Issue by bossley9** [oscarotero/vento#27]
Vento and Lume each use different Deno `std` library versions: Vento currently uses `std@0.210.0` while Lume uses `std@0.212.0`. This means that if you try to vendor dependencies, you will download duplicates of the standard library.

Would it be possible to always ensure the standard library versions of Vento and Lume are synced? This isn't really an issue per se but a nice to have.

**Comment by oscarotero** [comment]
It's not easy to keep the std library in sync. For now, the only workaround I can think of is using an import map to redirect `0.210` to `0.2.12`.

I hope when `std` library is finally stable, there won't be a new version every 1-2 weeks and `std@1.0.0` will keep unchanged for long time 🙏 .
