### ISSUE TITLE
Publishing of editor plugin on `open-vsx.org`

### ISSUE THREAD

**Issue by mash-graz** [oscarotero/vento#30]
Please publish the editor extension also on [open-vsx.org](https://open-vsx.org/).

Users of more privacy preserving variants of `vscodium` or strict open source related linux distributions otherwise have to install your plugin in a rather clumsy manner and do not get automatic updates.

**Comment by oscarotero** [comment]
Done: https://open-vsx.org/extension/oscarotero/vento-syntax
The process was a bit tedious but I could finally publish it.
